// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package userstore

import (
	"time"
)

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	Password    string
	PhoneNumber string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
