// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package grpcservice

import ()

type User struct {
	ID          string
	Email       string
	Password    string
	DateCreated string
}
